version: "3"

services:
  canwatch:
    build: .
    volumes:
      - .:/app
    networks:
      - backend
    environment:
      PORT: 80
    ports:
      - "9004:80"
    command: bash -c 'npm install && npm start'

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
