version: "3"

services:
  canwatch:
    build: .
    volumes:
      - .:/app
    networks:
      - backend
    environment:
      PORT: 80
    ports:
      - "9004:80"
    command: bash -c 'npm install && npm start'

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  mongo:
    image: "mongo:3"
    networks:
      - logfacility

  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    networks:
      - logfacility

  graylog:
    image: graylog/graylog:2.3.0-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    networks:
      - logfacility
      - backend
    ports:
      - "9000:9000"

networks:
  backend:
  logfacility:
