apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: canWatch
  name: canWatch
spec:
  replicas: 2
  selector:
    name: canWatch
  template:
    metadata:
      labels:
        name: canWatch
    spec:
      dnsPolicy: Default
      containers:
        - name: canWatch
          image: <../Dockerfile>
          resources:
            limits:
              cpu: 1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: 80
            - name: LOGLEVEL
              value: 'info'
            - name: GREYLOG
              value: 'true'
            - name: GREYLOG_HOST
              value: '<facility url>'
            - name: GREYLOG_PORT
              value: '<port>'
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 3
